### ISSUE TITLE
wy-form-message conflict for nameControl

### ISSUE THREAD

**Issue by budparr** [webhook/webhook-cms#211] opened 2015-01-16 03:22 UTC
Instructions for the Name field don't show up for the user. It looks as though they're being completely overwritten by, I think, /app/templates/wh/content/type/edit.hbs around line 19-50ish with the "This page will live at" language.

instructions added
![screen shot 2015-01-15 at 10 21 36 pm](https://cloud.githubusercontent.com/assets/115347/5771135/f4f6d2aa-9d04-11e4-8fc8-3ef09d7389ea.png)

no show
![screen shot 2015-01-15 at 10 21 57 pm](https://cloud.githubusercontent.com/assets/115347/5771138/005c9e22-9d05-11e4-98d4-5c247fa3a991.png)

**Comment by snide** [comment] 2015-01-16 03:24
This is a duplicate of https://github.com/webhook/webhook-cms/issues/190

I'll try and fix it early next week. I know the issue.

**Closed by snide** 2015-01-16 03:24 UTC

**Comment by budparr** [comment] 2015-01-16 04:23
I went ahead and put in a PR to fix. Hope that's helpful. I did nothing to style it to differentiate from the slug messaging above, just placed it below.

**Comment by budparr** [comment] 2015-01-16 04:24
by the way - the PR wasn't meant to rush the fix, so take your time to review
